default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: gym_locator_development

test:
  <<: *default
  database: gym_locator_test

production:
  <<: *default
  database: gym_locator_production
  username: gym_locator
  password: <%= ENV["GYM_LOCATOR_DATABASE_PASSWORD"] %>
